# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }

##############################
### WINDOWS AND WORKSPACES ##
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = AlacrittyNmtui 
    match:title = AlacrittyNmtui
    float = on
    center = on
    size = 800 600
}

windowrule {
name = Satty 
    match:title = satty
    float = on
    center = on
    size = 1280 768
}

windowrule {
    name = float-nwg-displays
    match:class = ^(nwg-displays)$
    float = on
    opaque = on
    size = 1102 662
    center = on
}

windowrule {
    name = float_qbittorrent_all
    match:class = ^(org.qbittorrent.qBittorrent)$
    float = on
    center = on
    size = 650 450
}

windowrule {
    name = tile_qbittorrent_main
    match:class = ^(org.qbittorrent.qBittorrent)$
    match:title = ^(qBittorrent v).*$
    float = off
}

windowrule {
    name = steam-general
    match:class = ^(steam)$
    float = off
    opaque = on
}

windowrule {
    name = steam-main-window
    match:class = ^(steam)$
    match:title = ^(Steam)$
    size = 1100 600
    center = on
}

windowrule {
    name = steam-friends
    match:class = ^(steam)$
    match:title = ^(Friends List)$
    float = on
    size = 460 580
    center = on
}

windowrule {
    name = steam-settings
    match:class = ^(steam)$
    match:title = ^(Steam Settings)$
    float = on
    size = 1100 600
    center = on
}

windowrule {
    name = steam-special-offers
    match:class = ^(steam)$
    match:title = ^(Special Offers)$
    float = on
    center = on
}

windowrule {
    name = steam-idle
    match:class = ^(steam)$
    idle_inhibit = fullscreen
}

windowrule {
    name = cava 
    match:class = ^(cava)$
    float = on
    size = 791 488
    center = on
}

windowrule {
    name = btop
    match:title = ^(btop)$
    float = on
    size = 1080 607
    center = on
}


windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float on, match:class ^(waypaper)$
# rofi blur
layerrule = blur on, ignore_alpha 0, match:namespace rofi


