# : Manager [[[

[mgr]
cwd = { fg = "#e7e1e2" }

# Tab
tab_active = { fg = "#3c2b3c", bg = "#fce1f8", bold = true }
tab_inactive = { fg = "#f6dbf1", bg = "#261626" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#bdc87a", bg = "#bdc87a" }
marker_cut = { fg = "#e1e6c2", bg = "#e1e6c2" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e7ecc8", bg = "#e7ecc8" }

# Count
count_copied = { fg = "#191d07", bg = "#e1e6c2" }
count_cut = { fg = "#191d07", bg = "#e1e6c2" }
count_selected = { fg = "#3c2b3c", bg = "#e7ecc8" }

# Border
border_symbol = " "
border_style  = { fg = "#d9bfd5" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#3c2b3c", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#fce1f8", fg = "#3c2b3c", bold = true }
normal_alt  = { bg = "#4c454a", fg = "#cec3ca" }

# Select mode
select_main = { bg = "#d0c3cc", fg = "#362e35", bold = true }
select_alt  = { bg = "#4c454a", fg = "#cec3ca" }

# Unset mode
unset_main = { bg = "#e7ecc8", fg = "#2e331a", bold = true }
unset_alt  = { bg = "#4c454a", fg = "#cec3ca" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#fce1f8", bg = "#3b383a" }
progress_error = { fg = "#ffb4ab", bg = "#3b383a" }

# Permissions
permissions_t = { fg = "#8c6e83" }
permissions_w = { fg = "#b5c556" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#acba55" }
permissions_s = { fg = "#d761c1" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#fce1f8" }
active = { fg = "#e7ecc8", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#fce1f8" }
value = { fg = "#e7e1e2" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#fce1f8", bold = true, bg = "#151314" }
inactive = { fg = "#d0c3cc", bg = "#151314" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#fce1f8", bg = "#3c2b3c" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#fce1f8" }
title = {}
hovered = { fg = "#e1e6c2", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3b383a" }
cand = { fg = "#fce1f8" }
rest = { fg = "#3c2b3c" }
desc = { fg = "#e7e1e2" }
separator = " ▶ "
separator_style = { fg = "#e7e1e2" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e7e1e2" }
run = { fg = "#e7e1e2" }
footer = { fg = "#362e35", bg = "#d0c3cc" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e7ecc8" }
title_warn = { fg = "#fce1f8" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e7e1e2" },
    { name = "*/", fg = "#d9bfd5" },
]

# : ]]]
