# : Manager [[[

[mgr]
cwd = { fg = "#e2e2e3" }

# Tab
tab_active = { fg = "#0b3544", bg = "#b3d9ec", bold = true }
tab_inactive = { fg = "#c2e8fc", bg = "#001f2a" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff9e5f", bg = "#ff9e5f" }
marker_cut = { fg = "#ffdcc5", bg = "#ffdcc5" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#fec8a3", bg = "#fec8a3" }

# Count
count_copied = { fg = "#2f1400", bg = "#ffdcc5" }
count_cut = { fg = "#2f1400", bg = "#ffdcc5" }
count_selected = { fg = "#0b3544", bg = "#fec8a3" }

# Border
border_symbol = " "
border_style  = { fg = "#a7ccdf" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#0b3544", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#b3d9ec", fg = "#0b3544", bold = true }
normal_alt  = { bg = "#41484b", fg = "#c1c7cc" }

# Select mode
select_main = { bg = "#bac9d1", fg = "#253239", bold = true }
select_alt  = { bg = "#41484b", fg = "#c1c7cc" }

# Unset mode
unset_main = { bg = "#fec8a3", fg = "#49290e", bold = true }
unset_alt  = { bg = "#41484b", fg = "#c1c7cc" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#b3d9ec", bg = "#38393b" }
progress_error = { fg = "#ffb4ab", bg = "#38393b" }

# Permissions
permissions_t = { fg = "#618091" }
permissions_w = { fg = "#fc6e0c" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff802c" }
permissions_s = { fg = "#30b1f5" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#b3d9ec" }
active = { fg = "#fec8a3", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#b3d9ec" }
value = { fg = "#e2e2e3" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#b3d9ec", bold = true, bg = "#121415" }
inactive = { fg = "#bac9d1", bg = "#121415" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#b3d9ec", bg = "#0b3544" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#b3d9ec" }
title = {}
hovered = { fg = "#ffdcc5", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#38393b" }
cand = { fg = "#b3d9ec" }
rest = { fg = "#0b3544" }
desc = { fg = "#e2e2e3" }
separator = " ▶ "
separator_style = { fg = "#e2e2e3" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e2e2e3" }
run = { fg = "#e2e2e3" }
footer = { fg = "#253239", bg = "#bac9d1" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#fec8a3" }
title_warn = { fg = "#b3d9ec" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e2e2e3" },
    { name = "*/", fg = "#a7ccdf" },
]

# : ]]]
