$image = /home/ducky/Pictures/Background/wallhaven-e8e1xo.jpg


$background = rgba(121415ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2f3132ff)

$inverse_primary = rgba(3f6374ff)

$inverse_surface = rgba(e2e2e3ff)

$on_background = rgba(e2e2e3ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(0b3544ff)

$on_primary_container = rgba(032f3eff)

$on_primary_fixed = rgba(001f2aff)

$on_primary_fixed_variant = rgba(264b5bff)

$on_secondary = rgba(253239ff)

$on_secondary_container = rgba(d4e2ebff)

$on_secondary_fixed = rgba(101d23ff)

$on_secondary_fixed_variant = rgba(3b4950ff)

$on_surface = rgba(e2e2e3ff)

$on_surface_variant = rgba(c1c7ccff)

$on_tertiary = rgba(49290eff)

$on_tertiary_container = rgba(422309ff)

$on_tertiary_fixed = rgba(2f1400ff)

$on_tertiary_fixed_variant = rgba(633e22ff)

$outline = rgba(8b9296ff)

$outline_variant = rgba(41484bff)

$primary = rgba(b3d9ecff)

$primary_container = rgba(98bdd0ff)

$primary_fixed = rgba(c2e8fcff)

$primary_fixed_dim = rgba(a7ccdfff)

$scrim = rgba(000000ff)

$secondary = rgba(bac9d1ff)

$secondary_container = rgba(3b4950ff)

$secondary_fixed = rgba(d6e5edff)

$secondary_fixed_dim = rgba(bac9d1ff)

$shadow = rgba(000000ff)

$source_color = rgba(98bdd0ff)

$surface = rgba(121415ff)

$surface_bright = rgba(38393bff)

$surface_container = rgba(1e2021ff)

$surface_container_high = rgba(282a2bff)

$surface_container_highest = rgba(333536ff)

$surface_container_low = rgba(1a1c1dff)

$surface_container_lowest = rgba(0d0e10ff)

$surface_dim = rgba(121415ff)

$surface_tint = rgba(a7ccdfff)

$surface_variant = rgba(41484bff)

$tertiary = rgba(fec8a3ff)

$tertiary_container = rgba(e0ad89ff)

$tertiary_fixed = rgba(ffdcc5ff)

$tertiary_fixed_dim = rgba(f0bc97ff)

