$image = /home/ducky/Pictures/Background/wallhaven-e8e1xo.jpg


$background = rgba(151314ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(323031ff)

$inverse_primary = rgba(6c586bff)

$inverse_surface = rgba(e7e1e2ff)

$on_background = rgba(e7e1e2ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(3c2b3cff)

$on_primary_container = rgba(473546ff)

$on_primary_fixed = rgba(261626ff)

$on_primary_fixed_variant = rgba(544153ff)

$on_secondary = rgba(362e35ff)

$on_secondary_container = rgba(efe0eaff)

$on_secondary_fixed = rgba(211920ff)

$on_secondary_fixed_variant = rgba(4d444cff)

$on_surface = rgba(e7e1e2ff)

$on_surface_variant = rgba(cec3caff)

$on_tertiary = rgba(2e331aff)

$on_tertiary_container = rgba(383d23ff)

$on_tertiary_fixed = rgba(191d07ff)

$on_tertiary_fixed_variant = rgba(44492fff)

$outline = rgba(978e94ff)

$outline_variant = rgba(4c454aff)

$primary = rgba(fce1f8ff)

$primary_container = rgba(dfc5dbff)

$primary_fixed = rgba(f6dbf1ff)

$primary_fixed_dim = rgba(d9bfd5ff)

$scrim = rgba(000000ff)

$secondary = rgba(d0c3ccff)

$secondary_container = rgba(50464eff)

$secondary_fixed = rgba(eddee8ff)

$secondary_fixed_dim = rgba(d0c3ccff)

$shadow = rgba(000000ff)

$source_color = rgba(dfc5dbff)

$surface = rgba(151314ff)

$surface_bright = rgba(3b383aff)

$surface_container = rgba(211f20ff)

$surface_container_high = rgba(2c292bff)

$surface_container_highest = rgba(373435ff)

$surface_container_low = rgba(1d1b1cff)

$surface_container_lowest = rgba(0f0e0fff)

$surface_dim = rgba(151314ff)

$surface_tint = rgba(d9bfd5ff)

$surface_variant = rgba(4c454aff)

$tertiary = rgba(e7ecc8ff)

$tertiary_container = rgba(cbd0adff)

$tertiary_fixed = rgba(e1e6c2ff)

$tertiary_fixed_dim = rgba(c5caa7ff)

